# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/

# Install dependencies (separated for caching)
RUN pip install -r requirements.txt

# Install from pyproject.toml
RUN pip install -e .

# Run init_db.py when the container launches
CMD ["python", "src/graphics_db_server/scripts/init_db.py"]